### ISSUE TITLE
what is the difference between promise-concurrency and Promise.all()

### ISSUE THREAD

**Issue by reanote** [springuper/promise-concurrency#1]
what is the difference between promise-concurrency and Promise.all(), thanks

**Comment by springuper** [comment]
`Promise.all` will run all promises in parallel, even there are more than one hundred requests. To gain more control about the concurrency promise instances, you can use promise-concurrency.

You can check out the test cases to know more: https://github.com/springuper/promise-concurrency/blob/master/test/main.js.
